### ISSUE TITLE
Inkscape 1.0 et python 3

### ISSUE THREAD

**Issue by michelwend** [Rafafouille/inkscape_liaisons#1]
Bonjour,
Est-ce que la version en développement sera compatible avec Inkscape 1.0 et python 3 car le fichier.txt parle de python 2? En vous remerciant pour votre travail.

**Comment by Rafafouille** [comment]
Bonjour.

Pour le moment, cela ne marche que pour Inkscape 0.92 avec Python 2.
Je suis justement en train de finaliser l'extension pour cette version là (voir la branche "develop").

Je sais que la version 1.0 d'Inkscape (avec python 3) est sortie récemment, mais je n'ai pas eu le temps de m retourner...
Je pense faire cela au début de l'été.
En attendant, il faudra soit réinstaller Inkscape 0.92, soit attendre un peu...

PS : Vous pouvez suivre ça sur Github pendant le développement, mais la version finale sera prochainement mise sur le site de l'Éduction Nationale "Eduscol STI" : https://eduscol.education.fr/sti/
-- 
Raphaël ALLAIS

**Comment by michelwend** [comment]
Merci pour votre retour, j'attendrai donc votre développement du début de l'été pour l'installer sur inkscape 1.0 avec python 3. Bon courage et à bientôt.

**Comment by Rafafouille** [comment]
Bonjour.

Une première version d'extension pour Inkscape 1.00 est maintenant en ligne, dans la branche "Inkscape_1.00", disponible ici : https://github.com/Rafafouille/inkscape_liaisons/tree/inkscape_1.00

Il s'agit d'une adaptation "brute" de l'ancienne version (juste pour que cela fonctionne). Toutefois, la nouvelle version d'Inkscape permet de faire une interface un peu plus amicale, ce sur quoi je travaille. C'est cette future version qui sera la nouvelle version officielle sur Éduscol.

Cordialement.

**Comment by michelwend** [comment]
Merci à vous,
Bien cordialement
